### ISSUE TITLE
button loading 添加

### ISSUE THREAD

**Issue by liyatang** [gmfe/react-gm#135]
@JoeBBChen

**Comment by liyatang** [comment]
测试issue 评论啦啦啦啦

**Comment by JoeBBChen** [comment]
@liyatang 【button loading 添加】这个描述太不确定了，按照语义， 只要 `button` 包含 loading 状态就行了？
如果是，这样封装一个 button，还不如调用者自己写个 button 再加个 Loading 了，因为按照这个定义，button 里除了个 loading 状态，各种样式都要调用者自己写。
如果不是的话，那应该给调用者提供更完善的 Button 组件。这个组件首先是个 Button，Button 应该包含 size，也就是 类似于 large，default，small 等，还包含主题，比如 default，primary，这时候这些 size 怎么定义，这个主题怎么定义，有哪些，最后 loading 只是这个 Button 的其中一种形态而已。这样封装一个 button 才有意义吧？所以 size 的大小怎么定义，主题有哪些，这要不你告诉吧。要不你告诉我使用场景要包含哪些，不然我都无从下手，写的粗糙你又不接受。

**Comment by liyatang** [comment]
你要做其他功能上去也可以啊。不冲突的。   不做，直接写 <Button className="btn btn-sm btn-primart" 也没毛病。 做了 <Button sm primary> 就少写点代码而已
