### ISSUE TITLE
Sheet组件希望提供单选功能

### ISSUE THREAD

**Issue by fondadam** [gmfe/react-gm#197]
现在：
![image](https://user-images.githubusercontent.com/7132998/39165265-362f6660-47b6-11e8-94cb-d0531354718a.png)

--- 

希望提供单选功能：
![image](https://user-images.githubusercontent.com/7132998/39165276-416106f6-47b6-11e8-8701-b788bfc4a9dd.png)

**Comment by liyatang** [comment]
done
