### ISSUE TITLE
FilterSelect组件下拉选择问题

### ISSUE THREAD

**Issue by Realwate** [gmfe/react-gm#225]
[react-gm](http://gmfe.github.io/react-gm/build/#/doc/FilterSelect)可复现。
1. 多选交互逻辑
* 问题： 多选，带搜索框情况下。输入关键字，选择完一个item后，关键字会被清空，导致触发onSearch('')事件，onSearch中的业务代码导致list变化(比如清空list)。
* 解决：多选选择item后，不清空关键字？

2. 下拉遮挡问题 *具体如图所示*

![image](https://user-images.githubusercontent.com/12814045/41277844-ea0aec02-6e5a-11e8-9069-d7606f2062ed.png)
![image](https://user-images.githubusercontent.com/12814045/41277866-fa15cfea-6e5a-11e8-8869-0ab437ce9553.png)

**Comment by liyatang** [comment]
已沟通，非bug
