### ISSUE TITLE
SearchSelect组件多选版本样式问题

### ISSUE THREAD

**Issue by farzer** [gmfe/react-gm#30]
![issue](https://cloud.githubusercontent.com/assets/9881593/20421141/15791d62-ad9d-11e6-843e-4789ededf4c5.gif)

**Comment by liyatang** [comment]
![](http://7xlnio.com1.z0.glb.clouddn.com/public/16-11-18/19593815.jpg)

后续会调整成这样

**Comment by liyatang** [comment]
![](http://7xlnio.com1.z0.glb.clouddn.com/public/16-11-18/19593815.jpg)

后续会调整成这样

**Comment by farzer** [comment]
good， that's what i need :)

**Comment by farzer** [comment]
这个在新建销售单里面就要用到了，你考虑一下这个时间点调整哈

**Comment by liyatang** [comment]
done
