### ISSUE TITLE
(Filter)SearchSelect改进建议，随意喷

### ISSUE THREAD

**Issue by liyatang** [gmfe/react-gm#50]

**Comment by fondadam** [comment]
![image](https://cloud.githubusercontent.com/assets/7132998/23294892/ae5c44d4-faa8-11e6-8ab6-e54b41ae1204.png)

貌似有个bug，就是我设置了默认值，但刷新页面进去后，我在render里面明明看到输出了这个值，证明有这个值了，但SearchSelect还是没有正确显示出来，需要点一下SearchSelect输入框，才会渲染出来。

不知道是我代码使用上的问题，还是组件内部存在的问题，所以没有及时渲染出来。（正在看SearchSelect源码，看看能不能找出问题所在...

**Comment by liyatang** [comment]
@fondadam 提供key
