### ISSUE TITLE
SearchSelect组件有个bug

### ISSUE THREAD

**Issue by fondadam** [gmfe/react-gm#51]
bug： 给`SearchSelect`设置默认值时,若在`componentDidMount`或者`componentWillMount`设置好`selected`，进入页面页面并不会正确显示出默认值`selected`。（除非你focus一下`SearchSelect`然后再blur后才能正确显示出默认值`selected`）

看了下源码，发现问题貌似出在这里:
![image](https://cloud.githubusercontent.com/assets/7132998/23346735/d93180c6-fcd7-11e6-982a-763c0bd26bb8.png)
![image](https://cloud.githubusercontent.com/assets/7132998/23346738/e41c1ee2-fcd7-11e6-8dd7-655f2e781983.png)
所以我尝试修改了一下:
![image](https://cloud.githubusercontent.com/assets/7132998/23346765/18a05be2-fcd8-11e6-8327-79429c402560.png)

但demo上貌似没出现这个问题，是因为在`constructor`就设置好`selected`了。

**Comment by liyatang** [comment]
key
