### ISSUE TITLE
bug: NProgress

### ISSUE THREAD

**Issue by yongningfu** [gmfe/react-gm#81]
单单执行 NProgress的 end方法的时, 会发生出现一点点进度条，而不是整个进度条

### bug分析 
由于之前未执行start, 则当前container里面的没有 NProgress生成的dom， 执行ReactDom.render的时候，找不到NProgree对应的preComponent， 则不会按照刷新的逻辑执行，即不执行componentWillReceiveProps

### 修改建议  
当组件生成的时候，state设置成默认的percent属性， percent理解为 从多少百分比开始加载

class NProgress extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            **percent: this.props.percent || 0**
        };
        this.timer = null;
    }

**Comment by liyatang** [comment]
@yongningfu 非常感谢提出建议。 已提交到 react-gm@5.3.3。
