### ISSUE TITLE
增加阴影公共类

### ISSUE THREAD

**Issue by liyatang** [gmfe/react-gm#86]
已私下沟通

**Comment by JoeBBChen** [comment]
这部分抽不出来，因为我想不到有什么比较通用的地方。

box-shadow 不像 margin 、padding 等那样，有 left、right、top、bottom 那样，而且比较常用，可以抽出一些常用的出来。

`box-shadow：<阴影类型><X-offset><Y-offset><阴影模糊半径><阴影扩展半径><阴影扩展半径>`

可以通过设置多次（
类似于：
 `box-shadow：<阴影类型><X-offset><Y-offset><阴影模糊半径><阴影扩展半径><阴影扩展半径>, <阴影类型><X-offset><Y-offset><阴影模糊半径><阴影扩展半径><阴影扩展半径>`
）达到叠加的效果。

把浮层阴影抽出来后，其他并不常用。
可能一个网站用到的地方才两三处，可能每一处场景不一样，值也不一样，感觉都是看心情调值的  :expressionless: ，好像没什么通用情况可抽？

**Comment by liyatang** [comment]
那close
